create table if not exists public.book_press_reviews (
  id bigint generated by default as identity primary key,
  book_id bigint not null references public."data-books"(id) on delete cascade,
  source_field text not null,
  position integer not null default 0,
  author_name text not null default '',
  source_name text not null default '',
  source_date text not null default '',
  excerpt text not null default '',
  raw_attribution text not null default '',
  is_verified boolean not null default false,
  created_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists book_press_reviews_book_excerpt_attr_uidx
  on public.book_press_reviews (book_id, md5(excerpt), md5(raw_attribution));

create index if not exists book_press_reviews_book_position_idx
  on public.book_press_reviews (book_id, position);

alter table public.book_press_reviews enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'book_press_reviews'
      and policyname = 'rls-book-press-reviews'
  ) then
    create policy "rls-book-press-reviews"
      on public.book_press_reviews
      for select
      to public
      using (true);
  end if;
end
$$;

grant select on public.book_press_reviews to anon;
grant select on public.book_press_reviews to authenticated;
grant select on public.book_press_reviews to service_role;

create or replace function public.refresh_book_press_reviews()
returns integer
language plpgsql
as $$
declare
  inserted_count integer := 0;
begin
  delete from public.book_press_reviews;

  with source_rows as (
    select
      b.id as book_id,
      source_field,
      btrim(source_text) as source_text
    from public."data-books" b
    cross join lateral (
      values
        ('Résumé', coalesce(b."Résumé", '')),
        ('Sommaire', coalesce(b."Sommaire", '')),
        ('Quatrième. Couverture', coalesce(b."Quatrième. Couverture", ''))
    ) as sources(source_field, source_text)
    where position('Presse :' in coalesce(source_text, '')) > 0
  ),
  normalized_rows as (
    select
      book_id,
      source_field,
      regexp_replace(split_part(source_text, 'Presse :', 2), E'\r\n?', E'\n', 'g') as press_text
    from source_rows
  ),
  matched_reviews as (
    select
      book_id,
      source_field,
      ordinality::integer as position,
      btrim((match)[1]) as excerpt,
      btrim((match)[2]) as raw_attribution
    from normalized_rows
    cross join lateral regexp_matches(
      press_text,
      '«\s*([^»]+?)\s*»\s*\n\s*([^\n]+)',
      'g'
    ) with ordinality as matches(match, ordinality)
  )
  insert into public.book_press_reviews (
    book_id,
    source_field,
    position,
    author_name,
    source_name,
    source_date,
    excerpt,
    raw_attribution,
    is_verified
  )
  select
    book_id,
    source_field,
    position,
    case
      when position(',' in raw_attribution) > 0 then btrim(split_part(raw_attribution, ',', 1))
      else ''
    end as author_name,
    case
      when position(',' in raw_attribution) > 0 then btrim(substring(raw_attribution from position(',' in raw_attribution) + 1))
      else btrim(raw_attribution)
    end as source_name,
    '',
    excerpt,
    raw_attribution,
    true
  from matched_reviews
  where excerpt <> ''
    and raw_attribution <> ''
  on conflict do nothing;

  get diagnostics inserted_count = row_count;

  return inserted_count;
end;
$$;

select public.refresh_book_press_reviews();
