create extension if not exists pg_trgm with schema extensions;

alter table public."data-books" add column if not exists id bigint generated by default as identity;
alter table public."data-person" add column if not exists id bigint generated by default as identity;
alter table public."data-organism" add column if not exists id bigint generated by default as identity;

update public."data-books" set id = default where id is null;
update public."data-person" set id = default where id is null;
update public."data-organism" set id = default where id is null;

alter table public."data-books" alter column id set not null;
alter table public."data-person" alter column id set not null;
alter table public."data-organism" alter column id set not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public."data-books"'::regclass
      and conname = 'data-books_pkey'
  ) then
    alter table public."data-books" add constraint "data-books_pkey" primary key (id);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public."data-person"'::regclass
      and conname = 'data-person_pkey'
  ) then
    alter table public."data-person" add constraint "data-person_pkey" primary key (id);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public."data-organism"'::regclass
      and conname = 'data-organism_id_key'
  ) then
    alter table public."data-organism" add constraint "data-organism_id_key" unique (id);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'data-books'
      and policyname = 'rls-data-books'
  ) then
    create policy "rls-data-books"
      on public."data-books"
      for select
      to public
      using (true);
  end if;
end
$$;

create index if not exists "data-books_title_trgm_idx"
  on public."data-books"
  using gin (lower(coalesce("Titre", '')) gin_trgm_ops);

create index if not exists "data-organism_name_trgm_idx"
  on public."data-organism"
  using gin (lower(coalesce("Organisme", '')) gin_trgm_ops);

create index if not exists "data-person_name_trgm_idx"
  on public."data-person"
  using gin (lower(coalesce("Pr�nom Nom", '')) gin_trgm_ops);

create index if not exists "data-person_alt_name_trgm_idx"
  on public."data-person"
  using gin (lower(coalesce("Nom Pr�nom", '')) gin_trgm_ops);

create or replace function public.get_persons_page(
  p_page integer default 1,
  p_page_size integer default 13,
  p_search text default null
)
returns jsonb
language sql
stable
as $$
  with filtered as (
    select
      p.id,
      btrim(coalesce(nullif(p."Pr�nom Nom", ''), nullif(p."Nom Pr�nom", ''), '')) as name,
      btrim(coalesce(p."Type Personne", '')) as type,
      btrim(coalesce(p."Langue �criture", '')) as language,
      coalesce(p."Nb. Titres Originaux"::text, '0') as original_titles,
      coalesce(p."Nb. Titres Traduits"::text, '0') as translated_titles,
      coalesce(p."Nb. Langues Traduction"::text, '0') as translation_languages,
      coalesce(p."Nb. Prix Distinctions"::text, '0') as awards,
      coalesce(p."Nb. R��ditions R�guli�res"::text, '0') as regular_reissues,
      coalesce(p."Nb. R��ditions Poche"::text, '0') as pocket_reissues,
      coalesce(p."Nb. Pays Publication"::text, '0') as publication_countries
    from public."data-person" p
    where btrim(coalesce(nullif(p."Pr�nom Nom", ''), nullif(p."Nom Pr�nom", ''), '')) <> ''
      and btrim(coalesce(nullif(p."Pr�nom Nom", ''), nullif(p."Nom Pr�nom", ''), '')) !~ '^[?\s-]+$'
      and (
        p_search is null
        or btrim(p_search) = ''
        or lower(coalesce(p."Pr�nom Nom", '')) like '%' || lower(btrim(p_search)) || '%'
        or lower(coalesce(p."Nom Pr�nom", '')) like '%' || lower(btrim(p_search)) || '%'
      )
  ),
  paged as (
    select *
    from filtered
    order by lower(name), id
    offset greatest(p_page - 1, 0) * greatest(p_page_size, 1)
    limit greatest(p_page_size, 1)
  )
  select jsonb_build_object(
    'items',
    coalesce(
      (
        select jsonb_agg(
          jsonb_build_object(
            'name', name,
            'type', type,
            'language', language,
            'originalTitles', original_titles,
            'translatedTitles', translated_titles,
            'translationLanguages', translation_languages,
            'awards', awards,
            'regularReissues', regular_reissues,
            'pocketReissues', pocket_reissues,
            'publicationCountries', publication_countries
          )
          order by lower(name), id
        )
        from paged
      ),
      '[]'::jsonb
    ),
    'totalCount', (select count(*) from filtered),
    'databaseTotal', (select count(*) from public."data-person")
  );
$$;

create or replace function public.get_person_detail_by_name(
  p_name text
)
returns jsonb
language sql
stable
as $$
  with filtered as (
    select
      p.id,
      btrim(coalesce(nullif(p."Pr�nom Nom", ''), nullif(p."Nom Pr�nom", ''), '')) as name,
      btrim(coalesce(nullif(p."Nom Pr�nom", ''), nullif(p."Pr�nom Nom", ''), '')) as alternate_name,
      btrim(coalesce(p."Type Personne", '')) as type,
      btrim(coalesce(p."Langue �criture", '')) as language,
      btrim(coalesce(p."Ville de Naissance", '')) as birth_city,
      coalesce(p."Date de Naissance"::text, '') as birth_date,
      btrim(coalesce(p."Lieu de D�c�s", '')) as death_place,
      btrim(coalesce(p."Date de D�c�s", '')) as death_date,
      btrim(coalesce(p."Pays de R�sidence", '')) as residence,
      btrim(coalesce(p."Activit� Professionnelle", '')) as professional_activity,
      btrim(coalesce(p."Biographie", '')) as biography,
      coalesce(p."Nb. Titres Originaux"::text, '0') as original_titles,
      coalesce(p."Nb. Titres Traduits"::text, '0') as translations,
      coalesce(p."Nb. Langues Traduction"::text, '0') as publication_languages,
      btrim(coalesce(p."Type Contribution", '')) as bibliography_type,
      btrim(coalesce(p."Langue Traduction", '')) as bibliography_language,
      btrim(coalesce(p."Titre", '')) as bibliography_title,
      btrim(coalesce(p."Ann�e Publication", '')) as bibliography_year,
      btrim(coalesce(p."Cote Livre", '')) as bibliography_issue
    from public."data-person" p
    where btrim(coalesce(nullif(p."Pr�nom Nom", ''), nullif(p."Nom Pr�nom", ''), '')) <> ''
      and btrim(coalesce(nullif(p."Pr�nom Nom", ''), nullif(p."Nom Pr�nom", ''), '')) !~ '^[?\s-]+$'
  ),
  target as (
    select *
    from filtered
    where name = btrim(coalesce(p_name, ''))
       or alternate_name = btrim(coalesce(p_name, ''))
    order by case when name = btrim(coalesce(p_name, '')) then 0 else 1 end, id
    limit 1
  )
  select (
    select jsonb_build_object(
      'name', name,
      'alternateName', alternate_name,
      'type', type,
      'language', language,
      'birthInfo', concat_ws(', ', nullif(birth_city, ''), nullif(birth_date, '')),
      'deathInfo', concat_ws(', ', nullif(death_place, ''), nullif(death_date, '')),
      'residence', residence,
      'professionalActivity', professional_activity,
      'biography', biography,
      'bibliographyStats', jsonb_build_object(
        'originalTitles', original_titles,
        'translations', translations,
        'publicationLanguages', publication_languages
      ),
      'bibliographyRows',
      case
        when bibliography_type <> ''
          or bibliography_language <> ''
          or bibliography_title <> ''
          or bibliography_year <> ''
          or bibliography_issue <> ''
        then jsonb_build_array(
          jsonb_build_object(
            'type', bibliography_type,
            'language', bibliography_language,
            'title', bibliography_title,
            'year', bibliography_year,
            'issue', bibliography_issue
          )
        )
        else '[]'::jsonb
      end,
      'stats', jsonb_build_object(
        'cardsFound', (select count(*) from filtered),
        'databaseContains', (select count(*) from public."data-person")
      )
    )
    from target
  );
$$;

create or replace function public.get_default_person_detail()
returns jsonb
language sql
stable
as $$
  with filtered as (
    select
      p.id,
      btrim(coalesce(nullif(p."Pr�nom Nom", ''), nullif(p."Nom Pr�nom", ''), '')) as name,
      btrim(coalesce(nullif(p."Nom Pr�nom", ''), nullif(p."Pr�nom Nom", ''), '')) as alternate_name,
      btrim(coalesce(p."Type Personne", '')) as type,
      btrim(coalesce(p."Langue �criture", '')) as language,
      btrim(coalesce(p."Ville de Naissance", '')) as birth_city,
      coalesce(p."Date de Naissance"::text, '') as birth_date,
      btrim(coalesce(p."Lieu de D�c�s", '')) as death_place,
      btrim(coalesce(p."Date de D�c�s", '')) as death_date,
      btrim(coalesce(p."Pays de R�sidence", '')) as residence,
      btrim(coalesce(p."Activit� Professionnelle", '')) as professional_activity,
      btrim(coalesce(p."Biographie", '')) as biography,
      coalesce(p."Nb. Titres Originaux"::text, '0') as original_titles,
      coalesce(p."Nb. Titres Traduits"::text, '0') as translations,
      coalesce(p."Nb. Langues Traduction"::text, '0') as publication_languages,
      btrim(coalesce(p."Type Contribution", '')) as bibliography_type,
      btrim(coalesce(p."Langue Traduction", '')) as bibliography_language,
      btrim(coalesce(p."Titre", '')) as bibliography_title,
      btrim(coalesce(p."Ann�e Publication", '')) as bibliography_year,
      btrim(coalesce(p."Cote Livre", '')) as bibliography_issue
    from public."data-person" p
    where btrim(coalesce(nullif(p."Pr�nom Nom", ''), nullif(p."Nom Pr�nom", ''), '')) <> ''
      and btrim(coalesce(nullif(p."Pr�nom Nom", ''), nullif(p."Nom Pr�nom", ''), '')) !~ '^[?\s-]+$'
  ),
  target as (
    select *
    from filtered
    order by lower(alternate_name), id
    limit 1
  )
  select (
    select jsonb_build_object(
      'name', name,
      'alternateName', alternate_name,
      'type', type,
      'language', language,
      'birthInfo', concat_ws(', ', nullif(birth_city, ''), nullif(birth_date, '')),
      'deathInfo', concat_ws(', ', nullif(death_place, ''), nullif(death_date, '')),
      'residence', residence,
      'professionalActivity', professional_activity,
      'biography', biography,
      'bibliographyStats', jsonb_build_object(
        'originalTitles', original_titles,
        'translations', translations,
        'publicationLanguages', publication_languages
      ),
      'bibliographyRows',
      case
        when bibliography_type <> ''
          or bibliography_language <> ''
          or bibliography_title <> ''
          or bibliography_year <> ''
          or bibliography_issue <> ''
        then jsonb_build_array(
          jsonb_build_object(
            'type', bibliography_type,
            'language', bibliography_language,
            'title', bibliography_title,
            'year', bibliography_year,
            'issue', bibliography_issue
          )
        )
        else '[]'::jsonb
      end,
      'stats', jsonb_build_object(
        'cardsFound', (select count(*) from filtered),
        'databaseContains', (select count(*) from public."data-person")
      )
    )
    from target
  );
$$;

create or replace function public.get_organizations_page(
  p_page integer default 1,
  p_page_size integer default 13,
  p_search text default null
)
returns jsonb
language sql
stable
as $$
  with filtered as (
    select
      o.id,
      btrim(coalesce(o."Organisme", '')) as name,
      btrim(coalesce(o."Type", '')) as type,
      btrim(coalesce(o."Date_Creation", '')) as creation_date,
      btrim(coalesce(o."Pays", '')) as country,
      coalesce(o."Nb_Titres"::text, '0') as published_titles,
      coalesce(o."Nb_Auteurs"::text, '0') as published_authors
    from public."data-organism" o
    where btrim(coalesce(o."Organisme", '')) <> ''
      and btrim(coalesce(o."Organisme", '')) !~ '^[?\s-]+$'
      and (
        p_search is null
        or btrim(p_search) = ''
        or lower(coalesce(o."Organisme", '')) like '%' || lower(btrim(p_search)) || '%'
      )
  ),
  paged as (
    select *
    from filtered
    order by lower(name), id
    offset greatest(p_page - 1, 0) * greatest(p_page_size, 1)
    limit greatest(p_page_size, 1)
  )
  select jsonb_build_object(
    'items',
    coalesce(
      (
        select jsonb_agg(
          jsonb_build_object(
            'name', name,
            'type', type,
            'creationDate', creation_date,
            'country', country,
            'publishedTitles', published_titles,
            'publishedAuthors', published_authors
          )
          order by lower(name), id
        )
        from paged
      ),
      '[]'::jsonb
    ),
    'totalCount', (select count(*) from filtered),
    'databaseTotal', (select count(*) from public."data-organism")
  );
$$;

create or replace function public.get_organization_detail_by_name(
  p_name text
)
returns jsonb
language sql
stable
as $$
  with filtered as (
    select
      o.id,
      btrim(coalesce(o."Organisme", '')) as name,
      btrim(coalesce(o."Type", '')) as type,
      btrim(coalesce(o."Date_Creation", '')) as creation_date,
      btrim(coalesce(o."Pays", '')) as country,
      coalesce(o."Nb_Titres"::text, '0') as published_titles,
      coalesce(o."Nb_Auteurs"::text, '0') as published_authors
    from public."data-organism" o
    where btrim(coalesce(o."Organisme", '')) <> ''
      and btrim(coalesce(o."Organisme", '')) !~ '^[?\s-]+$'
  ),
  target as (
    select *
    from filtered
    where name = btrim(coalesce(p_name, ''))
    order by id
    limit 1
  )
  select (
    select jsonb_build_object(
      'name', name,
      'synonym', name,
      'type', type,
      'creationDate', creation_date,
      'country', country,
      'publishedStats', jsonb_build_object(
        'titles', published_titles,
        'authors', published_authors
      ),
      'stats', jsonb_build_object(
        'cardsFound', (select count(*) from filtered),
        'databaseContains', (select count(*) from public."data-organism")
      )
    )
    from target
  );
$$;

create or replace function public.get_default_organization_detail()
returns jsonb
language sql
stable
as $$
  with filtered as (
    select
      o.id,
      btrim(coalesce(o."Organisme", '')) as name,
      btrim(coalesce(o."Type", '')) as type,
      btrim(coalesce(o."Date_Creation", '')) as creation_date,
      btrim(coalesce(o."Pays", '')) as country,
      coalesce(o."Nb_Titres"::text, '0') as published_titles,
      coalesce(o."Nb_Auteurs"::text, '0') as published_authors
    from public."data-organism" o
    where btrim(coalesce(o."Organisme", '')) <> ''
      and btrim(coalesce(o."Organisme", '')) !~ '^[?\s-]+$'
  ),
  target as (
    select *
    from filtered
    order by lower(name), id
    limit 1
  )
  select (
    select jsonb_build_object(
      'name', name,
      'synonym', name,
      'type', type,
      'creationDate', creation_date,
      'country', country,
      'publishedStats', jsonb_build_object(
        'titles', published_titles,
        'authors', published_authors
      ),
      'stats', jsonb_build_object(
        'cardsFound', (select count(*) from filtered),
        'databaseContains', (select count(*) from public."data-organism")
      )
    )
    from target
  );
$$;
